// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaxgbvdnjbzuhifwoayd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdheGdidmRuamJ6dWhpZndvYXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3NTQ0MzUsImV4cCI6MjA3NDMzMDQzNX0.EEq_tQX7kFGFs2L0ZZZYRPiEjfNEtcH5mjCeiQIJnGM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});